FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt 
COPY ./app/process.py /code/process.py
COPY ./app/demi-moore-model.pth /code/demi-moore-model.pth

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
